#ifndef LIB8266__D1MINI__H__
#define LIB8266__D1MINI__H__

#include "driver/gpio.h"

#define AHOY_D1MINI_PIN_SCK 14
#define AHOY_D1MINI_PIN_SCL 5
#define AHOY_D1MINI_PIN_SDA 4

#define AHOY_D1MINI_PIN_MISO 12
#define AHOY_D1MINI_PIN_MOSI 13

#define AHOY_D1MINI_PIN_D0 GPIO_NUM_16
#define AHOY_D1MINI_PIN_D1 GPIO_NUM_5
#define AHOY_D1MINI_PIN_D2 GPIO_NUM_4
#define AHOY_D1MINI_PIN_D3 GPIO_NUM_0
#define AHOY_D1MINI_PIN_D4 GPIO_NUM_2
#define AHOY_D1MINI_PIN_D5 GPIO_NUM_14
#define AHOY_D1MINI_PIN_D6 GPIO_NUM_12
#define AHOY_D1MINI_PIN_D7 GPIO_NUM_13
#define AHOY_D1MINI_PIN_D8 GPIO_NUM_15

#endif
